+ Make enesim LGPL + Fix cross-dev building + Add SVG logo

diff --git a/enesim/configure.in b/enesim/configure.in
--- a/enesim/configure.in
+++ b/enesim/configure.in
@@ -39,12 +39,15 @@ AC_SUBST(create_shared_lib)
 
 PKG_CHECK_MODULES(EINA, [eina >= 0.0.1])
 PKG_CHECK_MODULES(PNG, [libpng >= 0.22], [have_png="yes"], [have_png="no"])
-PKG_CHECK_MODULES(SDL, [sdl >= 1.2.10], [have_sdl="yes"], [have_sdl="no"])
+#PKG_CHECK_MODULES(SDL, [sdl >= 1.2.10], [have_sdl="yes"], [have_sdl="no"])
 
 build_example="no"
-if test "x$have_sdl" = "xyes" && test "x$have_png" = "xyes"; then 
+#if test "x$have_sdl" = "xyes" && test "x$have_png" = "xyes"; then 
+if test "x$have_png" = "xyes"; then 
 	build_example="yes"
 fi
+
+## TODO Bench
 
 ## Coverage
 AC_ARG_ENABLE([coverage],
@@ -91,7 +94,7 @@ AC_MSG_RESULT([$enable_coverage])
 ENESIM_SURFACE_FORMAT(argb8888_unpre, [yes])
 ENESIM_SURFACE_FORMAT(rgb888_a8, [no])
 ENESIM_SURFACE_FORMAT(rgb565_xa5, [no])
-ENESIM_SURFACE_FORMAT(rgb565_b1a3, [no])
+ENESIM_SURFACE_FORMAT(rgb565_b1a3, [yes])
 
 EXAMPLE_CFLAGS="$SDL_CFLAGS $PNG_CFLAGS"
 EXAMPLE_LIBS="$SDL_LIBS $PNG_LIBS"
@@ -104,6 +107,33 @@ ENESIM_CFLAGS="$EINA_CFLAGS $COVERAGE_CFLAGS"
 ENESIM_LIBS="$EINA_LIBS $COVERAGE_LIBS"
 AC_SUBST(ENESIM_CFLAGS)
 AC_SUBST(ENESIM_LIBS)
+
+## The tool directory
+## Code taken from texinfo
+if test "$cross_compiling" = no; then
+  native_tools=
+else
+  native_tools=tools
+  test -d "$native_tools" || mkdir "$native_tools"
+  confdir=`(cd "$srcdir";pwd)`
+  # Make sure the secondary configure won't fail with
+  # "error: source directory already configured".
+  rm -f config.status
+  AC_MSG_NOTICE([[Doing configure of native tools (${build}).]])
+  cd "$native_tools" || exit 1
+  # Run secondary configure in alternate environment or
+  # it gets the wrong CC etc.
+  # env -i gives this build host configure a clean environment;
+  # consequently, we have to re-initialize $PATH.
+  env -i CC="$BUILD_CC" AR="$BUILD_AR" RANLIB="$BUILD_RANLIB" \
+      PATH="$PATH" \
+      tools_only=1 \
+    ${confdir}/configure --build=${build} --host=${build} 
+  cd .. || exit 1
+  AC_MSG_NOTICE([[Continuing with main configure (${host}).]])
+fi
+AC_SUBST(native_tools)
+AM_CONDITIONAL(TOOLS_ONLY, [[test "x$tools_only" = x1]])
 
 ## Make the debug preprocessor configurable
 
